Repository Kabana-FE/Kabana, pull requests merged in 2025-06, with the labels that each got.

#36 ✨Feat: 아이콘 컴포넌트 생성
  eslint.config.mjs
  index.html
  public/favicon.ico
  public/favicon.svg
  src/assets/icons/.gitkeep
  src/assets/icons/AddBoxIcon.tsx
  src/assets/icons/AddIcon.tsx
  src/assets/icons/CalendarIcon.tsx
  src/assets/icons/ChevronIcon.tsx
  src/assets/icons/CloseIcon.tsx
  src/assets/icons/CrownIcon.tsx
  src/assets/icons/DotIcon.tsx
  src/assets/icons/EyeIcon.tsx
  src/assets/icons/EyeOffIcon.tsx
  src/assets/icons/GithubIcon.tsx
  src/assets/icons/MoreVertIcon.tsx
  src/assets/icons/NoInvitationIcon.tsx
  src/assets/icons/PencilIcon.tsx
  src/assets/icons/SearchIcon.tsx
  src/assets/icons/SettingIcon.tsx
  src/assets/icons/TriangleIcon.tsx
  src/assets/icons/types/index.ts
  src/assets/images/.gitkeep
  src/assets/images/ErrorImage.tsx
  src/assets/images/HorizontalLogo.tsx
  src/assets/images/LogoImage.tsx
  src/assets/images/LogoTextImage.tsx
  src/assets/images/VerticalLogo.tsx
  src/assets/images/landing_image.webp
  src/utils/getRotationOffset.ts
Labels: ✨Feat

#53 ✨Feat: 할일 생성하기 모달 컴포넌트 기초 UI 구현
  src/components/createTodo/colorList.ts
  src/components/createTodo/index.tsx
  src/components/createTodo/types/index.ts
  src/components/dialog/ButtonArea.tsx
  src/components/dialog/Close.tsx
  src/components/dialog/Content.tsx
  src/components/dialog/Root.tsx
  src/components/dialog/Title.tsx
  src/components/dialog/index.tsx
  src/components/dialog/types/index.ts
  src/components/tag/index.tsx
  src/components/tag/types/index.ts
  src/stores/modalSlice.ts
  src/stores/slices/modalSlice.ts
  src/stores/store.ts
  src/stores/types/modalSlice.ts
Labels: ✨Feat

#69 ✨Feat: 버튼 공통 컴포넌트 생성(customComp제외)
  src/components/button/index.tsx
  src/components/button/types/index.ts
Labels: ✨Feat

#91 ✨Feat: 페이지네이션 컴포넌트 생성
  src/components/pagination/index.tsx
  src/components/pagination/types/index.ts
Labels: ✨Feat

#122 ✨Feat: 내 대시보드 페이지 ui 구성
  src/pages/dashboards/DashboardList.tsx
Labels: ✨Feat

#121 ✨Feat: 할일 상세 모달 구현 및 할일 생성 모달 수정
  package.json
  pnpm-lock.yaml
  src/components/badge/index.tsx
  src/components/cardDetail/Comment.tsx
  src/components/cardDetail/index.tsx
  src/components/cardDetail/types/index.ts
  src/components/common/dialog/ButtonArea.tsx
  src/components/common/dialog/Close.tsx
  src/components/common/dialog/Content.tsx
  src/components/common/dialog/Root.tsx
  src/components/common/dialog/Title.tsx
  src/components/common/dialog/index.tsx
  src/components/common/dialog/types/index.ts
  src/components/createTodo/index.tsx
  src/components/createTodo/types/index.ts
  src/components/dialog/Close.tsx
  src/components/tag/index.tsx
  src/components/tag/types/index.ts
  src/constants/errors/uiErrors.ts
  src/schemas/dashboard.ts
  src/stores/slices/modalSlice.ts
  src/stores/types/modalSlice.ts
Labels: ✨Feat

#160 ✨Feat: Footer 컴포넌트 생성
  src/components/common/footer/index.tsx
Labels: ✨Feat

#166 ✨Feat: 내 대시보드 페이지 데이터 불러오기
  src/apis/invitation.ts
  src/components/dashboardItem/index.tsx
  src/components/invitationItem/index.tsx
  src/components/invitationItem/types/index.ts
  src/loaders/dashboard/listLoader.ts
  src/loaders/dashboard/types/index.ts
  src/pages/dashboards/DashboardList.tsx
  src/schemas/invitation.ts
Labels: ✨Feat

#181 ♻️Refactor: 마이페이지 공통 컴포넌트 적용 & 데이터 불러오기
  src/apis/user.ts
  src/constants/errors/uiErrors.ts
  src/loaders/myPage/myPageLoader.ts
  src/loaders/myPage/types/index.ts
  src/pages/user/Mypage.tsx
  src/schemas/user.ts
Labels: ♻️Refactor, ✨Feat

#158 ✨Feat: 개별 모달 컴포넌트
  src/apis/column.ts
  src/apis/invitation.ts
  src/components/colorSelector/index.tsx
  src/components/colorSelector/types/index.ts
  src/components/modal/CreateColumn.tsx
  src/components/modal/CreateDashboard.tsx
  src/components/modal/DeleteAlert.tsx
  src/components/modal/EditColumn.tsx
  src/components/modal/InviteMember.tsx
  src/components/modal/types/index.ts
  src/pages/landing/index.tsx
  src/schemas/column.ts
  src/schemas/invitation.ts
Labels: ✨Feat

#217 ✨Feat: layout guard
  src/constants/errors/uiErrors.ts
  src/layouts/Auth.tsx
  src/layouts/Dashboard.tsx
  src/layouts/Landing.tsx
  src/layouts/Simple.tsx
  src/loaders/authGuardLoader.ts
  src/loaders/rootLoader.ts
  src/loaders/types/index.ts
  src/main.tsx
  src/pages/auth/Signin.tsx
  src/pages/landing/index.tsx
  src/router/index.tsx
Labels: ♻️Refactor, ✨Feat

#204 ✨Feat: 마이페이지 기능 구현
  src/apis/auth.ts
  src/apis/base/request.ts
  src/apis/user.ts
  src/main.tsx
  src/pages/user/Mypage.tsx
  src/schemas/auth.ts
Labels: ✨Feat

#218 ✨Feat: 로그인 폼, 로그인 페이지 구현
  src/App.tsx
  src/components/loginForm/index.tsx
  src/layouts/Auth.tsx
  src/pages/auth/Signin.tsx
  src/schemas/auth.ts
Labels: 💄Style, ✨Feat

#199 ✨Feat: popover, dropdown 공통 컴포넌트
  index.html
  src/apis/dashboard.ts
  src/components/common/dialog/Root.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/dropdown/types/index.ts
  src/components/common/header/Dashboard.tsx
  src/components/common/popover/Content.tsx
  src/components/common/popover/Root.tsx
  src/components/common/popover/Trigger.tsx
  src/components/common/popover/index.ts
  src/components/common/popover/types/index.ts
  src/components/common/toast/Toast.tsx
  src/components/common/toast/ToastProvider.tsx
  src/constants/ui/index.ts
  src/hooks/usePopover.ts
  src/main.tsx
  src/pages/landing/index.tsx
  src/pages/test/index.tsx
  src/router/index.tsx
Labels: ✨Feat

#224 ✨Feat: 대시보드 수정페이지 페이지네이션
  src/apis/dashboard.ts
  src/components/dashboardEdit/invitations.tsx
  src/components/dashboardEdit/members.tsx
  src/components/dashboardEdit/types/index.ts
  src/components/pagination/index.tsx
  src/layouts/Dashboard.tsx
  src/loaders/dashboard/editLoader.ts
  src/loaders/dashboard/types/index.ts
  src/pages/dashboards/DashboardEdit.tsx
  src/pages/landing/index.tsx
  src/schemas/dashboard.ts
Labels: ✨Feat

#221 ✨Feat: 대시보드 상세 페이지 기초 UI 및 데이터 불러오기
  src/actions/dashboard/detailAction.ts
  src/apis/card.ts
  src/apis/column.ts
  src/apis/comment.ts
  src/components/cardDetail/Comment.tsx
  src/components/cardDetail/index.tsx
  src/components/cardDetail/types/index.ts
  src/components/cardList/CardItem.tsx
  src/components/cardList/CardList.tsx
  src/components/cardList/types/index.ts
  src/components/common/dialog/Root.tsx
  src/components/common/dialog/index.ts
  src/components/common/dialog/types/index.ts
  src/components/common/toast/ToastProvider.tsx
  src/components/createTodo/index.tsx
  src/components/createTodo/types/index.ts
  src/components/modal/CreateColumn.tsx
  src/components/modal/CreateDashboard.tsx
  src/components/modal/DeleteAlert.tsx
  src/components/modal/EditColumn.tsx
  src/components/modal/InviteMember.tsx
  src/components/modal/cardDetail/Comment.tsx
  src/components/modal/cardDetail/index.tsx
  src/components/modal/cardDetail/types/index.ts
  src/components/modal/createTodo/index.tsx
  src/components/modal/createTodo/types/index.ts
  src/components/modal/types/index.ts
  src/components/tag/index.tsx
  src/constants/ui/colorList.ts
  src/hooks/useToast.ts
  src/loaders/dashboard/detailLoader.ts
  src/loaders/dashboard/types/index.ts
  src/pages/dashboards/DashboardDetail.tsx
  src/pages/landing/index.tsx
  src/schemas/card.ts
  src/schemas/column.ts
  src/schemas/comment.ts
  src/schemas/dashboard.ts
Labels: ✨Feat

#235 ✨Feat: 랜딩페이지 생성
  src/assets/images/Landing1.png
  src/assets/images/Landing2.png
  src/assets/images/Landing3.png
  src/assets/images/Landing4.png
  src/assets/images/Landing5.png
  src/components/colorSelector/index.tsx
  src/components/modal/CreateDashboard.tsx
  src/layouts/Landing.tsx
  src/loaders/dashboard/types/index.ts
  src/pages/landing/index.tsx
  src/schemas/dashboard.ts
Labels: ✨Feat

#240 ✨Feat: 회원가입 폼, 회원가입 페이지 구현
  src/components/loginForm/index.tsx
  src/components/signupForm/index.tsx
  src/pages/auth/Signin.tsx
  src/pages/auth/Signup.tsx
  src/schemas/auth.ts
Labels: ✨Feat

#241 ✨ Feat: 내 대시보드 검색기능
  src/components/search/index.tsx
  src/components/search/types/index.ts
  src/pages/dashboards/DashboardList.tsx
Labels: ✨Feat

#242 ✨Feat: 대시보드 헤더 만들기
  src/components/common/header/Dashboard.tsx
  src/loaders/dashboard/detailLoader.ts
  src/loaders/dashboard/editLoader.ts
  src/loaders/dashboard/types/index.ts
  src/pages/dashboards/DashboardList.tsx
  src/router/index.tsx
Labels: ✨Feat

#255 ✨Feat: 랜딩페이지 헤더 추가
  src/components/common/header/Dashboard.tsx
  src/components/common/header/Landing.tsx
  src/pages/landing/index.tsx
Labels: ✨Feat

#244 ✨Feat: 툴팁과 사이드바 구현
  index.html
  src/App.tsx
  src/apis/dashboard.ts
  src/components/common/header/Dashboard.tsx
  src/components/common/sidebar/index.tsx
  src/components/common/tooltip/index.tsx
  src/components/common/tooltip/types/index.ts
  src/components/pagination/index.tsx
  src/components/pagination/types/index.ts
  src/hooks/types/index.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useToast.ts
  src/layouts/Dashboard.tsx
  src/loaders/authGuardLoader.ts
  src/loaders/rootLoader.ts
  src/loaders/types/index.ts
  src/main.tsx
  src/pages/dashboards/DashboardList.tsx
  src/schemas/dashboard.ts
  src/stores/index.ts
  src/stores/slices/authSlice.ts
  src/stores/slices/sidebarSlice.ts
  src/stores/types/index.ts
Labels: ✨Feat

#256 ✨Feat: 대시보드 수정페이지 기능 구현
  src/apis/dashboard.ts
  src/components/dashboardEdit/invitations.tsx
  src/components/dashboardEdit/members.tsx
  src/components/dashboardEdit/types/index.ts
  src/components/modal/CreateDashboard.tsx
  src/pages/dashboards/DashboardEdit.tsx
  src/schemas/dashboard.ts
Labels: ✨Feat

#259 ♻️Refactor: 마이페이지 이미지 업로드 수정
  src/apis/dashboard.ts
  src/components/common/header/Dashboard.tsx
  src/hooks/useToast.ts
  src/layouts/Dashboard.tsx
  src/loaders/authGuardLoader.ts
  src/main.tsx
  src/pages/dashboards/DashboardList.tsx
  src/pages/user/Mypage.tsx
Labels: ♻️Refactor

#263 ✨ Feat: 헤더 사이드바 수정
  src/components/common/header/Dashboard.tsx
  src/components/common/sidebar/index.tsx
  src/layouts/Dashboard.tsx
  src/pages/dashboards/DashboardList.tsx
Labels: ✨Feat

#266 ✨ Feat: todo edit 기능 구현
  src/actions/dashboard/detailAction.ts
  src/apis/card.ts
  src/components/cardList/CardItem.tsx
  src/components/common/header/Dashboard.tsx
  src/components/common/sidebar/index.tsx
  src/components/modal/EditTodo.tsx
  src/components/modal/cardDetail/index.tsx
  src/components/modal/createTodo/index.tsx
  src/components/modal/types/index.ts
  src/pages/dashboards/DashboardDetail.tsx
  src/schemas/card.ts
  src/schemas/comment.ts
Labels: ✨Feat

#280 ✨Feat: 데모 전 리팩토링
  src/App.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/dropdown/types/index.ts
  src/components/common/header/Dashboard.tsx
  src/components/common/popover/Trigger.tsx
  src/components/common/sidebar/Pagination.tsx
  src/components/common/sidebar/index.tsx
  src/components/common/toast/ToastTimer.tsx
  src/components/modal/EditTodo.tsx
  src/components/modal/cardDetail/index.tsx
  src/components/modal/createTodo/index.tsx
  src/components/pagination/index.tsx
  src/pages/dashboards/DashboardEdit.tsx
  src/pages/dashboards/DashboardList.tsx
Labels: 🐛Fix, ♻️Refactor
